import { z } from "zod";

// 最後にdb側で保存する際に必要なスキーマ
export const characterSheetSchema = z.object({
	// basic info
	basic: z.object({
		occupation: z.string().min(1, "職業を選択してください"),
		age: z.number({ required_error: "年齢を入力してください" }),
		gender: z.enum(["man", "woman", "else"]),
	}),
	// abilities
	ability: z.object({
		strength: z.number(),
		constitution: z.number(),
		power: z.number(),
		dexterity: z.number(),
		appearance: z.number(),
		size: z.number(),
		intelligence: z.number(),
		education: z.number(),
		san: z.number(),
		fortune: z.number(),
		idea: z.number(),
		knowledge: z.number(),
		durability: z.number(),
		magicPoint: z.number(),
		vocationalSkillPoints: z.number(),
		hobbySkillPoints: z.number(),
		damageBonus: z.number(),
	}),

	skills: z.object({
		combat: z.object({
			dodge: z.number(),
			kick: z.number(),
			grapple: z.number(),
			punch: z.number(),
			headbutt: z.number(),
			throw: z.number(),
			martialArts: z.number(),
			handgun: z.number(),
			submachineGun: z.number(),
			shotgun: z.number(),
			machineGun: z.number(),
			rifle: z.number(),
		}),
		investigation: z.object({
			firstAid: z.number(),
			locksmith: z.number(),
			hide: z.number(),
			conceal: z.number(),
			listen: z.number(),
			sneak: z.number(),
			photography: z.number(),
			psychoanalysis: z.number(),
			track: z.number(),
			climb: z.number(),
			library: z.number(),
			spot: z.number(),
		}),
		action: z.object({
			drive: z.number(),
			mechanicalRepair: z.number(),
			operateHeavyMachinery: z.number(),
			ride: z.number(),
			swim: z.number(),
			craft: z.number(),
			pilot: z.number(),
			jump: z.number(),
			electricalRepair: z.number(),
			navigate: z.number(),
			disguise: z.number(),
		}),
		negotiation: z.object({
			fastTalk: z.number(),
			credit: z.number(),
			persuade: z.number(),
			bargain: z.number(),
			nativeLanguage: z.number(),
			otherLanguage: z.number(),
		}),
		knowledge: z.object({
			medicine: z.number(),
			occult: z.number(),
			chemistry: z.number(),
			cthulhuMythos: z.number(),
			art: z.number(),
			accounting: z.number(),
			archaeology: z.number(),
			computer: z.number(),
			psychology: z.number(),
			anthropology: z.number(),
			biology: z.number(),
			geology: z.number(),
			electronics: z.number(),
			astronomy: z.number(),
			naturalHistory: z.number(),
			physics: z.number(),
			law: z.number(),
			pharmacy: z.number(),
			history: z.number(),
		}),
	}),
});
