import type { Metadata } from "next";
import "@/styles/globals.css";
import { geistMono } from "@/styles/fonts";

export const metadata: Metadata = {
  title: "TRPG Tools",
  description: "Generated by ITOU",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className="bg-background">{children}</body>
    </html>
  );
}
