import type { Metadata } from "next";
import "@/styles/globals.css";
import { GeistSans } from "geist/font/sans";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/components/theme-provider";
import { Toaster } from "@/components/ui/sonner"
import { NuqsAdapter as NuqsNextAppRouterAdapter } from 'nuqs/adapters/next'

export const metadata: Metadata = {
  title: "TRPG Tools",
  description: "Generated by ITOU",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja" suppressHydrationWarning>
      <head>
        <script src="https://unpkg.com/react-scan/dist/auto.global.js" async />
      </head>
      <body className={cn("bg-background font-sans antialiased", GeistSans)}>
        <NuqsNextAppRouterAdapter>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange>
            {children}
          </ThemeProvider>
          <Toaster />
        </NuqsNextAppRouterAdapter>
      </body>
    </html>
  );
}
